name: "QHub validate linter - Pull Request"

on:
  pull_request:
    branches:
      - master
    paths:
      - "qhub-config.yaml"

env:
  GITHUB_TOKEN: {{ '${{ secrets.GITHUB_TOKEN }}' }}

jobs:
  qhub-validate:
    name: 'Qhub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
        with:
          token: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install qhub
        run: |
          pip install qhub==0.2.3
          pip install gitpython
          pip install pygithub
      - name: 'Qhub Linterfy'
        env: 
          REPO_NAME: {{ '${{ github.repository }}' }}
          PR_ID: {{ '$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")' }}
        run: |
          qhub validate --enable-commenting